import React from "react";

const OccupationOptions = () => {
  const occupationOptions = [
    { value: "Mahasiswa", label: "Mahasiswa" },
    { value: "Wiraswasta", label: "Wiraswasta" },
    { value: "Pelajar", label: "Pelajar" },
    { value: "Ibu Rumah Tangga", label: "Ibu Rumah Tangga" },
    { value: "Tidak Bekerja", label: "Tidak Bekerja" },
    { value: "Pegawai Negri Sipil", label: "Pegawai Negri Sipil" },
    { value: "Pensiun", label: "Pensiun" },
    { value: "TNI", label: "TNI" },
    { value: "Kepolisian RI", label: "Kepolisian RI" },
    { value: "Pedagang", label: "Pedagang" },
    { value: "Petani", label: "Petani" },
    { value: "Nelayan", label: "Nelayan" },
    { value: "Buruh", label: "Buruh" },
    { value: "Pengacara", label: "Pengacara" },
    { value: "Dokter", label: "Dokter" },
    { value: "Bidan", label: "Bidan" },
    { value: "Perawat", label: "Perawat" },
    { value: "Apoteker", label: "Apoteker" },
    { value: "Psikolog", label: "Psikolog" },
    { value: "Guru", label: "Guru" },
    { value: "Industri", label: "Industri" },
    { value: "Peternak", label: "Peternak" },
    { value: "Karyawan Swasta", label: "Karyawan Swasta" },
    { value: "Karyawan BUMN", label: "Karyawan BUMN" },
    { value: "Karyawan BUMD", label: "Karyawan BUMD" },
    { value: "Pendeta", label: "Pendeta" },
    { value: "Imam Masjid", label: "Imam Masjid" },
    { value: "Ustadz/Ustadzah", label: "Ustadz/Ustadzah" },
    { value: "Biarawati", label: "Biarawati" },
    { value: "Walikota", label: "Walikota" },
    { value: "Wakil Walikota", label: "Wakil Walikota" },
    { value: "Pilot", label: "Pilot" },
    { value: "Juru Masak", label: "Juru Masak" },
    { value: "Dosen", label: "Dosen" },
    { value: "Notaris", label: "Notaris" },
    { value: "Akuntan", label: "Akuntan" },
    { value: "Arsitek", label: "Arsitek" },
    { value: "Konsultan", label: "Konsultan" },
    { value: "Sopir", label: "Sopir" },
    { value: "Pembantu Rumah Tangga", label: "Pembantu Rumah Tangga" },
    { value: "Perangkat Desa", label: "Perangkat Desa" },
    { value: "Kepala Desa", label: "Kepala Desa" },
    { value: "Tukang Jahit", label: "Tukang Jahit" },
    { value: "Tukang Listrik", label: "Tukang Listrik" },
    { value: "Tukang Kayu", label: "Tukang Kayu" },
    { value: "Tukang Besi", label: "Tukang Besi" },
    { value: "Tukang Cukur", label: "Tukang Cukur" },
    { value: "Penata Rias", label: "Penata Rias" },
    { value: "Penata Busana", label: "Penata Busana" },
    { value: "Penata Rambut", label: "Penata Rambut" },
    { value: "Mekanik", label: "Mekanik" },
    { value: "Seniman", label: "Seniman" },
    { value: "Penterjemah", label: "Penterjemah" },
  ];

  return occupationOptions;
};

export default OccupationOptions;
